use_default_settings: true

search:
  formats:
    - html
    - json
  default_lang: "all"
  safe_search: 0

server:
  secret_key: "debug_key_for_now" 
  limiter: false
  image_proxy: true

outgoing:
  request_timeout: 20.0
  connect_timeout: 20.0

engines:
  - name: wikipedia
    engine: wikipedia
    disabled: false
  - name: qwant
    engine: qwant
    disabled: false
  - name: mojeek
    engine: mojeek
    disabled: false
  - name: google
    engine: google
    use_mobile_ui: true
  - name: duckduckgo
    engine: duckduckgo
  - name: brave
    engine: brave
    disabled: true
