use_default_settings: true

search:
  formats:
    - html
    - json
  default_lang: "all"
  safe_search: 0

server:
  secret_key: "debug_key_for_now" 
  limiter: false
  image_proxy: true

outgoing:
  request_timeout: 60.0
  connect_timeout: 60.0
  proxies:
    http:
      - http://user354025:qr0zet@102.129.221.253:5217
      - http://user354025:qr0zet@181.215.71.126:5217
      - http://user354025:qr0zet@77.83.195.196:5217
      - http://user354025:qr0zet@181.215.71.233:5217
      - http://user354025:qr0zet@102.129.221.248:5217
      - http://user354025:qr0zet@140.99.236.73:5217
      - http://user354025:qr0zet@146.103.19.83:5217
      - http://user354025:qr0zet@23.94.132.38:5217
      - http://user354025:qr0zet@23.94.132.83:5217
      - http://user354025:qr0zet@23.94.132.88:5217
    https:
      - http://user354025:qr0zet@102.129.221.253:5217
      - http://user354025:qr0zet@181.215.71.126:5217
      - http://user354025:qr0zet@77.83.195.196:5217
      - http://user354025:qr0zet@181.215.71.233:5217
      - http://user354025:qr0zet@102.129.221.248:5217
      - http://user354025:qr0zet@140.99.236.73:5217
      - http://user354025:qr0zet@146.103.19.83:5217
      - http://user354025:qr0zet@23.94.132.38:5217
      - http://user354025:qr0zet@23.94.132.83:5217
      - http://user354025:qr0zet@23.94.132.88:5217

engines:
  - name: wikipedia
    engine: wikipedia
    disabled: false
  - name: google
    engine: google
    disabled: false
    use_mobile_ui: true
  - name: brave
    engine: brave
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    disabled: true
  - name: qwant
    engine: qwant
    disabled: true
  - name: mojeek
    engine: mojeek
    disabled: true
  - name: startpage
    engine: startpage
    disabled: true
